// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQZ8He6p4LC0nhQFMxI7g3hiHPbDIxPw',
    appId: '1:940838714576:web:dc48cc4757ddff417532d5',
    messagingSenderId: '940838714576',
    projectId: 'classmate-4904f',
    authDomain: 'classmate-4904f.firebaseapp.com',
    storageBucket: 'classmate-4904f.firebasestorage.app',
    measurementId: 'G-FMSCWCB8ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdL0Ztzb3K19uUUcsfN-jS_d-iK9T9jmQ',
    appId: '1:940838714576:android:1f0ff836cdf1d9d47532d5',
    messagingSenderId: '940838714576',
    projectId: 'classmate-4904f',
    storageBucket: 'classmate-4904f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirbgzylhlGYwWUv5X3j1axYTfDQjQd8A',
    appId: '1:940838714576:ios:a46dbedfd07d58ea7532d5',
    messagingSenderId: '940838714576',
    projectId: 'classmate-4904f',
    storageBucket: 'classmate-4904f.firebasestorage.app',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDirbgzylhlGYwWUv5X3j1axYTfDQjQd8A',
    appId: '1:940838714576:ios:a46dbedfd07d58ea7532d5',
    messagingSenderId: '940838714576',
    projectId: 'classmate-4904f',
    storageBucket: 'classmate-4904f.firebasestorage.app',
    iosBundleId: 'com.example.classmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVQZ8He6p4LC0nhQFMxI7g3hiHPbDIxPw',
    appId: '1:940838714576:web:577915f9f34aec1d7532d5',
    messagingSenderId: '940838714576',
    projectId: 'classmate-4904f',
    authDomain: 'classmate-4904f.firebaseapp.com',
    storageBucket: 'classmate-4904f.firebasestorage.app',
    measurementId: 'G-LD770ZT5T4',
  );
}
